### PR TITLE
Updated to work with Python 3 as well as Django 2. Working as of 3/20…

### PR DESCRIPTION
**Pull request by avlewis**
…/2019

### CODE REVIEW

**Comment by EugeneDae** [comment]
@avlewis Thank you so much! <3

**Comment by EugeneDae** [comment]
@avlewis If you want to maintain this in the future, I can transfer the repo to you.

**Comment by avlewis** [comment]
Yeah that’d be great!

**Comment by EugeneDae** [comment]
@avlewis "avlewis/django-multifilefield already exists" -- please delete / rename the fork on your account, then I will be able to transfer this

**Comment by avlewis** [comment]
I deleted my fork. Should be good to go!

**Pull request merged**
